spring.application.name=recovery-service
server.port=8081

spring.threads.virtual.enabled=true

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

services.decision.base-url=http://localhost:8082
services.payment.base-url=http://localhost:8083
services.audit.base-url=http://localhost:8084